# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the stable/proj7 branch
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # run every week

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CONAN_USERNAME: CHM
  CONAN_CHANNEL: stable
  CONAN_UPLOAD: "http://conan.snowcast.ca:8081/artifactory/api/conan/chm"
  CONAN_LOGIN_USERNAME: "github"
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: "1"
  CONAN_REQUEST_TIMEOUT: 600
  CONAN_RETRY: 30
  CONAN_RETRY_WAIT: 60

  MAKEFLAGS: "-j2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.cfg.os }}
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        cfg:
          - {os: "ubuntu-18.04", compiler: "gcc", version: 7}
          - {os: "ubuntu-18.04", compiler: "gcc", version: 9}
          - {os: "ubuntu-18.04", compiler: "gcc", version: 10}
          - {os: "ubuntu-20.04", compiler: "gcc", version: 9}
          - {os: "ubuntu-20.04", compiler: "gcc", version: 10}
          - {os: "macos-10.15", compiler: "apple-clang", version: "12.0"}
        lib-version: ["2.6"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install conan --upgrade
          pip install conan_package_tools

      - name: Setup conan
        run: |
          conan profile new default --detect
          conan config install https://github.com/Chrismarsh/conan-config.git

          if [ "$RUNNER_OS" == "Linux" ]; then
            conan profile update settings.os.distro="$CFG_OS" default
          else
            conan profile update settings.os.version=`echo "$CFG_OS" | cut -d'-' -f2` default
          fi
          cat ~/.conan/profiles/default
        env:
          CFG_OS: ${{matrix.cfg.os}}

      - name: Update apt-get
        if: startsWith( matrix.cfg.os, 'ubuntu' )
        run: |
          sudo apt-get update
          sudo env ACCEPT_EULA=Y apt-get upgrade -y


      - name: env linux
        if: startsWith( matrix.cfg.os, 'ubuntu' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_GCC_VERSIONS: ${{ matrix.cfg.version }}
          CC: gcc-${{ matrix.cfg.version }}
          CXX: g++-${{ matrix.cfg.version }}

      - name: env macos
        if: startsWith( matrix.cfg.os, 'macos' )
        uses: allenevans/set-env@v2.0.0
        with:
          CONAN_APPLE_CLANG_VERSIONS: ${{ matrix.cfg.version }}

      - name: Build
        run: |
          python build.py
        env:
          CONAN_REFERENCE: gsl/${{ matrix.lib-version}}



